spring:
  application:
    name: consumer
server:
  port: 8201


eureka:
  instance:
    prefer-ip-address: true #注册服务的时候使用服务的IP注册
  client:
    service-url:
      defaultZone: http://eureka8761.com:8761/eureka/,http://eureka8762.com:8762/eureka/,http://eureka8763.com:8763/eureka/
    register-with-eureka: false
# 服务降级需要的
feign:
  hystrix:
    enabled: true