server:
  port: 8763
eureka:
  instance:
    #hostname: eureka-server #eureka实例的主机名
    hostname: eureka8763.com #集群模式，
    # 优化监控那显示
    instance-id: eureka-server #自定义服务名称
    prefer-ip-address: true #访问地址可以显示IP

  client:
    register-with-eureka: false  #不把自己注册到eureka上 不做高可用的情况下写成false
    fetch-registry: false #不从eureka上获取来获取服务的注册信息
    service-url:
      # 单机模式下写：http://${eureka.instance.hostname}:${server.port}/eureka/
      # 集群模式的话，多个用逗号隔开，写其他集群地址，
      defaultZone: http://eureka8761.com:8761/eureka/,http://eureka8762.com:8762/eureka/

